# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4cdd53607a176411a0daa753abc627cfcb1d16cb81d7a53545d5a9a21ac46aac17ad4ff19ded7a1f946b9e348768f8f75e2a284644d35f89cddb8caf4c59bb1

test:
  secret_key_base: 8b460eb266502a9648f8a23febc11f6332d430eb20bf3613435e83f74d68ee8ab87a321c5cf803f8b4d3baa8634598ea17e14f169f7a9eba9740767cec183ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
